# This file was generated by GoReleaser. DO NOT EDIT.
cask "fxn" do
  desc "Function Node is the core software for providers."
  homepage "https://github.com/fxnlabs/function-node"
  version "0.0.32"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fxn"

  on_macos do
    on_intel do
      url "https://github.com/fxnlabs/function-node/releases/download/0.0.32/function-node_0.0.32_darwin_amd64.tar.gz"
      sha256 "7608624be7a7d148bbea80f1785e25502621d22b622551de28846c989ba791d2"
    end
    on_arm do
      url "https://github.com/fxnlabs/function-node/releases/download/0.0.32/function-node_0.0.32_darwin_arm64.tar.gz"
      sha256 "ff3120e6445b5e71c5452d01b3796a5679f1023ac78d2e00056827c37473c920"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/fxnlabs/function-node/releases/download/0.0.32/function-node_0.0.32_linux_amd64.tar.gz"
      sha256 "5a1d9049e0d49bdd4440088675d64e5388278cff3f77cc76aa6095ab81a01c59"
    end
    on_arm do
      url "https://github.com/fxnlabs/function-node/releases/download/0.0.32/function-node_0.0.32_linux_arm64.tar.gz"
      sha256 "15bbd365f0f962154713086cd0b81b2bd64427c4a191e90f1722eae4d6488860"
    end
  end

  # No zap stanza required
end
