# This file was generated by GoReleaser. DO NOT EDIT.
cask "fxn" do
  desc "Function Node is the core software for providers."
  homepage "https://github.com/fxnlabs/function-node"
  version "0.0.30"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fxn"

  on_macos do
    on_intel do
      url "https://github.com/fxnlabs/function-node/releases/download/0.0.30/function-node_0.0.30_darwin_amd64.tar.gz"
      sha256 "c969a7207e1c145f0d9b39e6ee475f4b4b362e0d0d6c5c6b6a6014c2f11323f2"
    end
    on_arm do
      url "https://github.com/fxnlabs/function-node/releases/download/0.0.30/function-node_0.0.30_darwin_arm64.tar.gz"
      sha256 "8bcc85d2adc3ca1a0de66ee982aea653687a51bf813dd99fa03c12dbee954f8e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/fxnlabs/function-node/releases/download/0.0.30/function-node_0.0.30_linux_amd64.tar.gz"
      sha256 "087b23232987c3ac41a514d2165e3487f93485da7967849b762785f0071a7ba3"
    end
    on_arm do
      url "https://github.com/fxnlabs/function-node/releases/download/0.0.30/function-node_0.0.30_linux_arm64.tar.gz"
      sha256 "c6c37b283e2a1c1a7d9a74640cd9e80b0d350e822b11d0a22af277d0653e7c69"
    end
  end

  # No zap stanza required
end
