# This file was generated by GoReleaser. DO NOT EDIT.
cask "fxn" do
  desc "Function Node is the core software for providers."
  homepage "https://github.com/fxnlabs/function-node"
  version "0.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fxn"

  on_macos do
    on_intel do
      url "https://github.com/fxnlabs/function-node/releases/download/0.1.1/function-node_0.1.1_darwin_amd64.tar.gz"
      sha256 "d3d52ab5b87b311ddcf3f4ee6ef0f58f58766dc385ebb9c54d1f4ed0fa92b8e0"
    end
    on_arm do
      url "https://github.com/fxnlabs/function-node/releases/download/0.1.1/function-node_0.1.1_darwin_arm64.tar.gz"
      sha256 "865ace4995d817ef403c9fd600bb1e9c0d2f5992299072ccaaab7314372902a9"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/fxnlabs/function-node/releases/download/0.1.1/function-node_0.1.1_linux_amd64.tar.gz"
      sha256 "bf5336907dc18bb1e7a7c290f5bc4bf65e655c75615835aa7a9851d156832fd2"
    end
    on_arm do
      url "https://github.com/fxnlabs/function-node/releases/download/0.1.1/function-node_0.1.1_linux_arm64.tar.gz"
      sha256 "847aca755638b38d8fddc319874a41ff23ba2ef493548ffbc96050f71cbc08d3"
    end
  end

  # No zap stanza required
end
